services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Point to the Dockerfile for the FastAPI app
    container_name: fastapi_app
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  vaultx_agent:
    build:
      context: .
      dockerfile: Dockerfile.langgraph  # Point to the Dockerfile for the LangGraph agent
    container_name: vaultx_agent
    command: langgraph dev --host 0.0.0.0
    ports:
      - "2024:2024"  # Adjust if your agent listens on a different port